from enum import Enum

from config import ROUTE_MENU_PATH, ROUTE_TRAINER, ROUTE_SETTINGS, ROUTE_BACK


class Route(Enum):
    ROUTE_MENU = ROUTE_MENU_PATH
    ROUTE_TRAINER = ROUTE_TRAINER
    ROUTE_SETTINGS = ROUTE_SETTINGS
    ROUTE_BACK = ROUTE_BACK
